FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /source
COPY site/*.csproj ./site/
RUN dotnet restore ./site/Site.csproj
COPY ./site/ ./site/
RUN dotnet build ./site/Site.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app ./
RUN apt-get update && apt-get install -y curl
EXPOSE 8080
ENTRYPOINT ["dotnet", "MarketingSite.dll"]