FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /source
COPY api/*.csproj ./api/
RUN dotnet restore ./api/Api.csproj
COPY ./api/ ./api/
RUN dotnet build ./api/Api.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app ./
RUN apt-get update && apt-get install -y curl
EXPOSE 8080
ENTRYPOINT ["dotnet", "MarketingApi.dll"]